imports:
    - { resource: parameters.yml }

services:
    minty.seeds.controller.main:
        class: minty\seeds\controller\main_controller
        arguments:
            - '@auth'
            - '@user'
            - '@request'        
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@files.factory'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%' 
            - '@?phpbbstudio.aps.manager'

    minty.seeds.controller.acp:
        class: minty\seeds\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    minty.seeds.controller.ucp:
        class: minty\seeds\controller\ucp_controller
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'

    minty.seeds.service:
        class: minty\seeds\service
        arguments:
            - '@user'
            - '%minty.seeds.tables.seeds_table%'

    minty.seeds.listener:
        class: minty\seeds\event\main_listener
        arguments:
            - '@auth'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '@template'
            - '@config'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    minty.seeds.aps.action.insert_seed:
        class: minty\seeds\aps\insert_seed
        shared: false
        tags:
            - { name: phpbbstudio.aps.action, order: 0 }
    
    minty.seeds.aps.action.update_seed:
        class: minty\seeds\aps\update_seed
        shared: false
        tags:
            - { name: phpbbstudio.aps.action, order: 1 }

    minty.seeds.aps.action.delete_seed:
        class: minty\seeds\aps\delete_seed
        shared: false
        tags:
            - { name: phpbbstudio.aps.action, order: 2 }

    minty.seeds.aps.action.insert_breeder:
        class: minty\seeds\aps\insert_breeder
        shared: false
        tags:
            - { name: phpbbstudio.aps.action, order: 3 }
    
    minty.seeds.aps.action.update_breeder:
        class: minty\seeds\aps\update_breeder
        shared: false
        tags:
            - { name: phpbbstudio.aps.action, order: 4 }

    minty.seeds.aps.action.delete_breeder:
        class: minty\seeds\aps\delete_breeder
        shared: false
        tags:
            - { name: phpbbstudio.aps.action, order: 5 }
